services:
  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    restart: unless-stopped
    ports:
      - 82:82
      - 445:445
    volumes:
      - /path/to/heimdall/config:/config

