global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'homelab-monitor'
    environment: 'production'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus-server'

  # Raspberry Pi metrics via Node Exporter
  - job_name: 'raspberry-pi'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'raspberry-pi'

  # MikroTik RB750GL via SNMP
  - job_name: 'mikrotik'
    static_configs:
      - targets:
        - ${ROUTER_IP}
    metrics_path: /snmp
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: snmp-exporter:9116
      - source_labels: [__param_target]
        target_label: device
        replacement: 'mikrotik-rb750gl'
