global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'homelab-monitor'
    environment: 'production'

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          instance: 'prometheus-server'

  # Raspberry Pi metrics via Node Exporter
  - job_name: 'raspberry-pi'
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          instance: 'raspberry-pi'
